### ISSUE TITLE
Getting started using the API

### ISSUE THREAD

**Issue by Ricardomol** [TheMich4/iracing-api#1]
Hello, and first of all, thanks for writing this API.

I know it is still a WIP, but I'd like to use it in an Express project.

Can you help me get started with it?

How do you import it, log in and send a simple request?

This is what I've come up with, but I can't even manage to import your module correctly.

```js
const express = require('express');
import {IracingAPI} from "iracing-api/lib/index.js";

const app = express();
const port = 3000;
const irUser = 'FOO@gmail.com';
const irPass = 'BAR';

app.get('/', (req, res) => {
  IracingAPI.login(irUser, irPass);
  res.send('Hello World!');
});
```

**Comment by TheMich4** [comment]
Hello.

This is just a wrapper for the General Availability iRacing API which goal is to simplify the usage and add type safety.
Full documentation of this API can be found on [iRacing Forums](https://forums.iracing.com/discussion/15068/general-availability-of-data-api/p1).

For the simplest usage you could try something like this to get car data from `data/car/get`  endpoint:

``` typescript
import IracinAPI from "iracing-api";

const irUser = 'FOO@gmail.com';
const irPass = 'BAR';

const main = async () => {
  const ir = new IracingAPI();

  // First you have to login to iracing using your credentials in order to be able to use the API.
  await ir.login(irUser, irPass);
  
  // Now you can use any endpoint, e.g. getCars
  const cars = await ir.getCars();

  console.log(cars);
}

main().then(() => 'Done')
```

I hope it's clear enough for you. If you have any more questions feel free to ask.

Note that since it is still work in progress the might be some breaking changes introduced.

**Comment by Ricardomol** [comment]
@TheMich4 that worked, thanks for the example and explanation!
